package com.sunway.ws.module.erp.business.lcb;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.sunway.ws.module.erp.business.lcb.bean.LcbServiceBean;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-01-22T13:57:35.231+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "urn:seg:ecc:ca:ppms", name = "SI_SEG_PPMS_CA_LCB_REQ_A_OUT")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LcbWSInterface {

    @WebMethod(operationName = "SI_SEG_PPMS_CA_LCB_REQ_A_OUT", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void siSEGPPMSCALCBREQAOUT(
        @WebParam(partName = "MT_SEG_PPMS_CA_LCB_REQ", name = "MT_SEG_PPMS_CA_LCB_REQ", targetNamespace = "urn:seg:ecc:ca:ppms")
        LcbServiceBean mtSEGPPMSCALCBREQ
    );
}
