package com.sunway.ws.module.erp.business.feedback;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.sunway.ws.module.erp.business.cgjh.bean.CgjhFdServerBean;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2015-11-24T09:40:51.458+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "urn:seg:ecc:ca:ppms", name = "SI_SEG_PPMS_CA_PR_RESP_OUT")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CgjhFeedbackWSInterface {

    @WebMethod(operationName = "SI_SEG_PPMS_CA_PR_RESP_OUT", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void siSEGPPMSCAPRRESPOUT(
        @WebParam(partName = "MT_SEG_PPMS_CA_PR_RESP", name = "MT_SEG_PPMS_CA_PR_RESP", targetNamespace = "urn:seg:ecc:ca:ppms")
        CgjhFdServerBean cgjhFdServerBean
    );
}
